#!/bin/bash
set -e

die() {
    echo >&2 "ERROR: $*"
    exit 1
}

B=""
while [ $# -gt 1 ]; do
    case "$1" in
        --dir)
            B="$2"
            shift
            ;;
        --)
            shift
            break
            ;;
        -*)
            die "unknown flag '$1'"
            ;;
        *)
            break
            ;;
    esac
    shift
done

[ -d "$B" ] || die "directory '$B' does not exist"
[ -r "$B"/conf/oe-env ] || die "file '$B'/conf/oe-env does not exist"

OEENV=$(cat "$B/conf/oe-env")
[ -r "$OEENV" ] || die "cannot read '$OEENV', get '$B/conf/oe-env' fixed!"

. "$OEENV" "$B"
"$@"
