#!/bin/sh
set -e

die() {
    echo >&2 "ERROR: $*"
    exit 1
}

GEN=""
DST=""
PORT=""
while [ $# -gt 1 ]; do
    case "$1" in
        --sstate-gen)
            GEN="$2"
            shift
            ;;
        --rsync-to)
            DST="$2"
            shift
            ;;
        --ssh-port)
            PORT="$2"
            shift
            ;;
        --)
            shift
            break
            ;;
        -*)
            die "unknown flag '$1'"
            ;;
        *)
            break
            ;;
    esac
    shift
done

[ -n "$GEN" ] || die "missing --sstate-gen"
[ -n "$DST" ] || die "missing --rsync-to"

if [ -n "$PORT" ]; then
    export RSYNC_RSH="ssh -p '$PORT'"
fi

SSTATE=~/sstate-cache-"${GEN}"

rsync -aH --info=stats2 --safe-links "$@" \
      $SSTATE \
      "$DST"
